server:
   port: ${port:9000}
   
   
spring:
  application:
    name: user-proxy-server

logging:
  level: 
    com.netflix.discovery: 'OFF'
    org.springframework.cloud: 'DEBUG'
 
eureka:
  client:
     registerWithEureka: true
     fetchRegistry: true
     serviceUrl:
       defaultZone: http://localhost:9761/eureka/
  instance:
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
   